ConferenceRoomBooking.Web/Controllers/ConferenceRoom/ConferenceRoomBookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessAL.DbContext;
using DataAL.Models;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Authorization;
using ConferenceRoomBooking.Web.Helper;

namespace ConferenceRoomBooking.Web.Controllers
{
    [Authorize]
    public class ConferenceRoomBookingsController : Controller
    {
        private readonly RepositoryContext _context;
        private readonly string _storagePath;

        public ConferenceRoomBookingsController(RepositoryContext context, IWebHostEnvironment env)
        {
            _context = context;
            _storagePath = Path.Combine(env.WebRootPath, "bookings");
            if (!Directory.Exists(_storagePath))
                Directory.CreateDirectory(_storagePath);
        }

        // GET: ConferenceRoomBookings
        public async Task<IActionResult> Index(int flag)
        {
            var repositoryContext = _context.ConferenceRoomBooking.Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
            var finalData = repositoryContext;
            switch (flag)
            {
                case 100:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date == DateTime.Now.Date).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
                case 1:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date >= DateTime.Now.Date).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
                case -1:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date < DateTime.Now.Date).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
                case 7:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date <= DateTime.Now.Date.AddDays(flag) && b.DateOfEvent.Date >= DateTime.Now.Date).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
                case 14:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date <= DateTime.Now.Date.AddDays(flag) && b.DateOfEvent.Date >= DateTime.Now.Date).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
                default:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date >= DateTime.Now.Date).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
            }
            return View(await finalData.OrderBy(b => b.DateOfEvent).ToListAsync());
        }

        // GET: ConferenceRoomBookings
        public async Task<IActionResult> Upcoming(int flag)
        {
            var repositoryContext = _context.ConferenceRoomBooking.Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
            var finalData = repositoryContext;
            switch (flag)
            {
                case -1:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date >= DateTime.Now.Date && (b.ChairpersonId != 1 && b.ChairpersonId != 2)).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
                case 1:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date >= DateTime.Now.Date && b.ChairpersonId == flag).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
                case 2:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date >= DateTime.Now.Date && b.ChairpersonId == flag).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
                default:
                    finalData = repositoryContext.Where(b => b.DateOfEvent.Date >= DateTime.Now.Date).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
                    break;
            }
            return View(await finalData.OrderBy(b => b.DateOfEvent).ToListAsync());
        }

        // GET: ConferenceRoomBookings
        public async Task<IActionResult> Today()
        {
            var repositoryContext = _context.ConferenceRoomBooking.Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
            var finalData = repositoryContext.Where(b => b.DateOfEvent.Date == DateTime.Now.Date).Include(c => c.Chairperson).Include(c => c.EventType).Include(c => c.Office);
            return View(await finalData.OrderBy(b => b.DateOfEvent).ToListAsync());
        }

        // GET: ConferenceRoomBookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conferenceRoomBooking = await _context.ConferenceRoomBooking
                .Include(c => c.Chairperson)
                .Include(c => c.EventType)
                .Include(c => c.Office)
                .FirstOrDefaultAsync(m => m.ConferenceRoomBookingId == id);
            if (conferenceRoomBooking == null)
            {
                return NotFound();
            }

            return View(conferenceRoomBooking);
        }

        // GET: ConferenceRoomBookings/Create
        public IActionResult Create()
        {
            ViewData["ChairpersonId"] = WebHelper.GetChairPerson(_context);
            ViewData["EventTypeId"] = new SelectList(_context.EventType, "EventTypeId", "Name");
            ViewData["OfficeId"] = new SelectList(_context.Office, "OfficeId", "Name");
            return View();
        }

        // POST: ConferenceRoomBookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ConferenceRoomBookingId,DateOfEvent,StartTime,Subject,EventTypeId,Description,ChairpersonId,TentativeEndTime,OfficeId,IsPublished,CreatedByUserId,CreatedDate,ModifiedById,ModificationDate,ContactPersonMobile,ContactPersonaName,OfficeOrderUrl,ZoomMeetingId,ZoomMeetingPasscode,ZoomMeetingLink")] DataAL.Models.ConferenceRoomBooking conferenceRoomBooking, IFormFile file)
        {
            conferenceRoomBooking.IsPublished = true;
            conferenceRoomBooking.OfficeId = 1; // To be removed later
            conferenceRoomBooking.CreatedByUserId = 1;
            conferenceRoomBooking.CreatedDate = DateTime.Now;
            conferenceRoomBooking.ModifiedById = 1;
            conferenceRoomBooking.ModificationDate = DateTime.Now;
            conferenceRoomBooking.StartTime = "string.Empty";
            ModelState.Remove("StartTime");
            ModelState.Remove("NewDateOfEvent");
            var singleBooking = await _context.ConferenceRoomBooking.Where(b => b.DateOfEvent == conferenceRoomBooking.DateOfEvent).FirstOrDefaultAsync();
            if (singleBooking != null)
            {
                ModelState.AddModelError(string.Empty, "A booking already exists for the selected date. Please choose a different date.");
                ViewData["ChairpersonId"] = WebHelper.GetChairPerson(_context, conferenceRoomBooking.ChairpersonId);
                ViewData["EventTypeId"] = new SelectList(_context.EventType, "EventTypeId", "Name", conferenceRoomBooking.EventTypeId);
                ViewData["OfficeId"] = new SelectList(_context.Office, "OfficeId", "Name", conferenceRoomBooking.OfficeId);
                return View(conferenceRoomBooking);
            }
            if (file != null && file.Length > 0)
            {
                var fileName = Guid.NewGuid() + "-" + file.Name + Path.GetExtension(file.FileName);
                var filePath = Path.Combine(_storagePath, fileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                    await file.CopyToAsync(stream);
                conferenceRoomBooking.OfficeOrderUrl = fileName;
                conferenceRoomBooking.OriginalName = file.FileName;
            }

            if (ModelState.IsValid)
            {
                _context.Add(conferenceRoomBooking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChairpersonId"] = WebHelper.GetChairPerson(_context, conferenceRoomBooking.ChairpersonId);
            ViewData["EventTypeId"] = new SelectList(_context.EventType, "EventTypeId", "Name", conferenceRoomBooking.EventTypeId);
            ViewData["OfficeId"] = new SelectList(_context.Office, "OfficeId", "Name", conferenceRoomBooking.OfficeId);
            return View(conferenceRoomBooking);
        }
        public async Task<IActionResult> Download(int id)
        {
            var doc = await _context.ConferenceRoomBooking.FindAsync(id);
            if (doc == null) return NotFound();

            var filePath = Path.Combine(_storagePath, doc.OfficeOrderUrl);
            if (!System.IO.File.Exists(filePath)) return NotFound();

            var mimeType = "application/octet-stream";
            return PhysicalFile(filePath, mimeType, doc.OriginalName);
        }

        // GET: ConferenceRoomBookings/Edit/5
        public async Task<IActionResult> Shift(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conferenceRoomBooking = await _context.ConferenceRoomBooking.FindAsync(id);
            if (conferenceRoomBooking == null)
            {
                return NotFound();
            }

ConferenceRoomBooking.Web/Views/ConferenceRoomBookings/Create.cshtml
@model DataAL.Models.ConferenceRoomBooking

@{
    ViewData["Title"] = "Create";
}

<h3>কনফারেন্স রুম বুকিং</h3>
<hr />

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h4 class="font-weight-bold mb-0">কনফারেন্স রুম বুকিং সংক্রান্ত তথ্য প্রদান</h4>
            </div>
            <div>
                <a asp-action="index" class="btn btn-outline-primary btn-icon-text btn-rounded btn-resize">
                    <i class="ti-arrow-left"></i>Back to list
                </a>
                <a asp-action="index" asp-controller="ConferenceRoomBookings" class="btn btn-outline-primary btn-icon-text btn-rounded btn-resize">
                    <i class="bi bi-house"></i>&nbsp;Dashboard
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                @* <h4 class="card-title">Add a Personal Information</h4> *@
                <div class="table-responsive pt-3">
                    @* <div asp-validation-summary="All" class="text-danger"></div> *@
                    <form asp-action="Create" method="post" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DateOfEvent" class="control-label"></label>
                                <input asp-for="DateOfEvent" class="form-control" />
                                <span asp-validation-for="DateOfEvent" class="text-danger"></span>
                            </div>
                        </div>
                        @*<div class="form-group">
                            <label asp-for="StartTime" class="control-label"></label>
                            <input asp-for="StartTime" class="form-control" />
                            <span asp-validation-for="StartTime" class="text-danger"></span>
                        </div>*@
                        <div class="form-group">
                            <label asp-for="Subject" class="control-label"></label>
                            <input asp-for="Subject" class="form-control" />
                            <span asp-validation-for="Subject" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="ChairpersonId" class="control-label"></label>
                                    <select asp-for="ChairpersonId" class="form-control" asp-items="ViewBag.ChairpersonId"></select>
                                </div>
                            </div>
                            @* <div class="col-md-6">
                                <br />
                                <button type="button" class="btn btn-outline-info btn-sm "><i class="bi bi-plus"></i> Add</button>
                            </div> *@
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="TentativeEndTime" class="control-label"></label>
                                <input asp-for="TentativeEndTime" class="form-control" />
                                <span asp-validation-for="TentativeEndTime" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EventTypeId" class="control-label"></label>
                                <select asp-for="EventTypeId" class="form-control" asp-items="ViewBag.EventTypeId"></select>
                            </div>
                        </div>
                        @* <div class="form-group">
                                <label asp-for="OfficeId" class="control-label"></label>
                                <select asp-for="OfficeId" class ="form-control" asp-items="ViewBag.OfficeId"></select>
                            </div>
                            <div class="form-group form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" asp-for="IsPublished" /> @Html.DisplayNameFor(model => model.IsPublished)
                                </label>
                            </div>
                            <div class="form-group">
                                <label asp-for="CreatedByUserId" class="control-label"></label>
                                <input asp-for="CreatedByUserId" class="form-control" />
                                <span asp-validation-for="CreatedByUserId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CreatedDate" class="control-label"></label>
                                <input asp-for="CreatedDate" class="form-control" />
                                <span asp-validation-for="CreatedDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ModifiedById" class="control-label"></label>
                                <input asp-for="ModifiedById" class="form-control" />
                                <span asp-validation-for="ModifiedById" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ModificationDate" class="control-label"></label>
                                <input asp-for="ModificationDate" class="form-control" />
                                <span asp-validation-for="ModificationDate" class="text-danger"></span>
                            </div> *@
                        <br />
                        <div class="accordion" id="accordionZoomMeeting">
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        <strong> Zoom অনলাইন সভার তথ্য (ঐচ্ছিক)</strong>
                                    </button>
                                </h2>
                                <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionZoomMeeting">
                                    <div class="accordion-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label asp-for="ZoomMeetingId" class="control-label"></label>
                                                    <input asp-for="ZoomMeetingId" class="form-control" />
                                                    <span asp-validation-for="ZoomMeetingId" class="text-danger"></span>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label asp-for="ZoomMeetingPasscode" class="control-label"></label>
                                                    <input asp-for="ZoomMeetingPasscode" class="form-control" />
                                                    <span asp-validation-for="ZoomMeetingPasscode" class="text-danger"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="ZoomMeetingLink" class="control-label"></label>
                                            <input asp-for="ZoomMeetingLink" class="form-control" />
                                            <span asp-validation-for="ZoomMeetingLink" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br />
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        <strong> আরও অপশন (ঐচ্ছিক)</strong>
                                    </button>
                                </h2>
                                <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label asp-for="ContactPersonaName" class="control-label"></label>
                                                    <input asp-for="ContactPersonaName" class="form-control" />
                                                    <span asp-validation-for="ContactPersonaName" class="text-danger"></span>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label asp-for="ContactPersonMobile" class="control-label"></label>
                                                    <input asp-for="ContactPersonMobile" class="form-control" />
                                                    <span asp-validation-for="ContactPersonMobile" class="text-danger"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="OfficeOrderUrl" class="control-label"></label>
                                            <input asp-for="OfficeOrderUrl" class="form-control" type="file" id="file" name="file" />
                                            <span asp-validation-for="OfficeOrderUrl" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <br />
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                    @* <div class="row">
    <div class="col-md-4">
    </div>
</div> *@
                </div>
            </div>
        </div>
    </div>
</div>

<br />
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ConferenceRoomBooking.Web/Views/ConferenceRoomBookings/Index.cshtml
@model IEnumerable<DataAL.Models.ConferenceRoomBooking>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Index";
    string message = "অনুষ্ঠানের সময়সূচী";
    int count = 1;
    var flag = HttpContextAccessor.HttpContext.Request.Query["flag"].ToString();
    switch (flag)
    {
        case "0":
            message = "আজকের অনুষ্ঠানের সময়সূচী";
            break;
        case "1":
            message = "সম্মেলন কক্ষে অনুষ্ঠানের সময়সূচী";
            break;
        case "-1":
            message = "পূর্বের অনুষ্ঠানের সময়সূচী";
            break;
        default:
            break;
    }
}

<h3>@message</h3>
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between align-items-center">
            <div>&nbsp;</div>
            <div>
                <a asp-action="create" class="btn btn-outline-primary btn-icon-text btn-rounded btn-resize">
                    <i class="ti-desktop"></i>&nbsp;কনফারেন্স রুম বুকিং দিন
                </a>
                <a asp-action="index" asp-controller="ConferenceRoomBookings" class="btn btn-outline-primary btn-icon-text btn-rounded btn-resize">
                    <i class="bi bi-house"></i>&nbsp;Dashboard
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                ক্রমিক
            </th>
            <th>তারিখ</th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfEvent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChairpersonId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TentativeEndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventTypeId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @(count++)
                </td>
                <td>
                    @item.DateOfEvent.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfEvent.TimeOfDay)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.ConferenceRoomBookingId">
                        @Html.DisplayFor(modelItem => item.Subject)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Chairperson.ChairpersonName) &nbsp; @(string.IsNullOrWhiteSpace(item.Chairperson.ShortDescription)?string.Empty: " (" + item.Chairperson.ShortDescription + ")")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TentativeEndTime.TimeOfDay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventType.Name)
                </td>
                <td>
                    <a asp-action="Shift" asp-route-id="@item.ConferenceRoomBookingId"><i class="bi bi-repeat text-danger"></i>Shift</a>
                    <a asp-action="Edit" asp-route-id="@item.ConferenceRoomBookingId"><i class="bi bi-pencil text-success"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.ConferenceRoomBookingId"><i class="bi bi-trash text-danger"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

ConferenceRoomBooking.Web/Views/ConferenceRoomBookings/Today.cshtml
@using DataAL.Models;
@model IEnumerable<ConferenceRoomBooking>

@{
    ViewData["Title"] = "আজকের অনুষ্ঠানের সময়সূচীসমূহ";
    List<ConferenceRoomBooking> meetings = Model.ToList();
}

<h3>আজকের অনুষ্ঠানের সময়সূচীসমূহ</h3>
<hr />

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <a asp-action="create" class="btn btn-outline-primary btn-icon-text btn-rounded btn-resize">
                    <i class="ti-desktop"></i>&nbsp;কনফারেন্স রুম বুকিং দিন
                </a>
            </div>
            <div>
                <a asp-controller="ConferenceRoomBookings" asp-action="index" asp-route-flag="100" class="btn btn-outline-info">আজকের অনুষ্ঠানের সময়সূচী (তালিকা) </a>
                <a asp-action="index" class="btn btn-outline-primary btn-icon-text btn-rounded btn-resize">
                    <i class="ti-arrow-left"></i>Back to list
                </a>
                <a asp-action="index" asp-controller="ConferenceRoomBookings" class="btn btn-outline-primary btn-icon-text btn-rounded btn-resize">
                    <i class="bi bi-house"></i>&nbsp;Dashboard
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    @* <h4 class="card-title">Add a Personal Information</h4> *@
    <div id="carouselExampleDark" class="carousel carousel-dark slide border">
        <div class="carousel-indicators">
            @{
                string isActive = "active";
                string isCurrent = "true";
                for (int i = 1; i <= meetings.Count; i++)
                {
                    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="@(i - 1)" class="@isActive" aria-current="@isCurrent" aria-label="@meetings[i - 1].Subject"></button>
                    isActive = string.Empty;
                    isCurrent = string.Empty;
                }
            }
        </div>

        <div class="carousel-inner">
            @{
                isActive = "active";
                for (int i = 0; i < meetings.Count; i++)
                {
                    <div class="carousel-item @isActive" data-bs-interval="1000" style="height: 200px !important;">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>
                                <a asp-action="Details" asp-route-id="@meetings[i].ConferenceRoomBookingId">
                                    @meetings[i].Subject
                                </a>
                                <br /><br />
                                @meetings[i].DateOfEvent
                            </h5>
                            <p>
                                @meetings[i].ContactPersonaName
                                <br />
                                @meetings[i].ContactPersonMobile
                            </p>
                        </div>
                    </div>
                    isActive = string.Empty;
                }
            }
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
<br />
<div>
    <a asp-action="index" class="btn btn-outline-primary btn-icon-text btn-rounded btn-resize">
        <i class="ti-arrow-left"></i>Back to list
    </a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}